import numpy as np
import matplotlib.pyplot as plt

def read_and_display_npz(file_path):
    """
    Read an .npz file generated by the Intan recording script and display its content.

    Args:
        file_path (str): Path to the .npz file.

    Returns:
        None
    """
    try:
        # Load the .npz file
        data = np.load(file_path)
        
        # Extract metadata and data
        dataBuffer = data['data']
        sampleRate = data['sampleRate'].item()  # Convert numpy scalar to Python scalar
        channels = data['channels']

        # Print metadata
        print(f"Sample Rate: {sampleRate} Hz")
        print(f"Channels: {channels}")
        print(f"Data Shape: {dataBuffer.shape}")

        # Plot each channel's data
        time_axis = np.arange(dataBuffer.shape[1]) / sampleRate  # Time in seconds
        for i, channel in enumerate(channels):
            plt.figure()
            plt.plot(time_axis, dataBuffer[i], label=f'Channel: {channel}')
            plt.title(f'Data from {channel}')
            plt.xlabel('Time (s)')
            plt.ylabel('Amplitude')
            plt.legend()
            plt.show()

    except Exception as e:
        print(f"Error reading file {file_path}: {e}")

def inspect_npz_file(file_path):
    """
    Inspect an .npz file to print its shape, included names, and a sample of the data.

    Args:
        file_path (str): Path to the .npz file.

    Returns:
        None
    """
    try:
        # Load the .npz file
        data = np.load(file_path)

        # Print all keys (names) in the .npz file
        print("Included names (keys):")
        for key in data.keys():
            print(f" - {key}")

        # Access specific keys and print details
        if 'data' in data:
            print("\nShape of data:")
            print(data['data'].shape)

            # Print a sample of the data (e.g., first 10 samples of the first channel)
            print("\nSample of the data (first 10 samples of the first channel):")
            print(data['data'][0, :10])

        if 'sampleRate' in data:
            print("\nSample rate:")
            print(data['sampleRate'].item())  # Convert numpy scalar to Python scalar

        if 'channels' in data:
            print("\nChannels:")
            print(data['channels'])

    except Exception as e:
        print(f"Error inspecting file {file_path}: {e}")

# Example usage
file_path = 'data/intan_data_20241220_123831.npz'  # replace
#read_and_display_npz(file_path)
inspect_npz_file(file_path)
